### PR TITLE
Adds 'coverage' subcommand

### PR DESCRIPTION
**Pull request by tostis-corning**
Adds support for unit test coverage tracking via 'coverage' package.

### CODE REVIEW

**Review by scizzorz — COMMENTED** [review]
Good suggestion - any reason to prefer `&&` instead of just using multiple lines for the extra commands?

**Comment by tostis-corning** [comment]
The && will stop execution of subsequent commands if one fails.
This will prevent the coverage reports from attempting generation if the coverage run fails.

**Comment by tostis-corning** [comment]
@scizzorz  I adjusted the formatting of the statements as we discussed.
I didn't realize each line would be executed individually, so I removed the &&s since they seem redundant here.

**Comment by scizzorz** [comment]
Yeah, it just takes that block string and writes it to a file, then executes that file as a shell script.

**Pull request merged**
